<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="3" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-10-28T07:11:10 IST" name="Suite" finished-at="2024-10-28T07:11:48 IST" duration-ms="37481">
    <groups>
      <group name="DataDriven">
        <method signature="TC02_LoginTestDDT.verify_LoginAccount(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_LoginTestDDT@21a21c64]" name="verify_LoginAccount" class="testCases.TC02_LoginTestDDT"/>
      </group> <!-- DataDriven -->
    </groups>
    <test started-at="2024-10-28T07:11:10 IST" name="Test" finished-at="2024-10-28T07:11:48 IST" duration-ms="37481">
      <class name="testCases.TC02_LoginTestDDT">
        <test-method is-config="true" signature="setUp(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_LoginTestDDT@21a21c64]" started-at="2024-10-28T07:11:11 IST" name="setUp" finished-at="2024-10-28T07:11:18 IST" duration-ms="7730" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verify_LoginAccount(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_LoginTestDDT@21a21c64]" started-at="2024-10-28T07:11:21 IST" name="verify_LoginAccount" data-provider="LoginData" finished-at="2024-10-28T07:11:23 IST" duration-ms="2688" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[EcPoK@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[EjW@544]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[valid]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_LoginAccount -->
        <test-method signature="verify_LoginAccount(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_LoginTestDDT@21a21c64]" started-at="2024-10-28T07:11:24 IST" name="verify_LoginAccount" data-provider="LoginData" finished-at="2024-10-28T07:11:26 IST" duration-ms="2037" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[YvnBm@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[sdu@494]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[invalid]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at testCases.TC02_LoginTestDDT.verify_LoginAccount(TC02_LoginTestDDT.java:53)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_LoginAccount -->
        <test-method signature="verify_LoginAccount(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_LoginTestDDT@21a21c64]" started-at="2024-10-28T07:11:26 IST" name="verify_LoginAccount" data-provider="LoginData" finished-at="2024-10-28T07:11:28 IST" duration-ms="2195" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[laksh@yahoo.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Lakshmi]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[invalid]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at testCases.TC02_LoginTestDDT.verify_LoginAccount(TC02_LoginTestDDT.java:53)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_LoginAccount -->
        <test-method signature="verify_LoginAccount(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_LoginTestDDT@21a21c64]" started-at="2024-10-28T07:11:28 IST" name="verify_LoginAccount" data-provider="LoginData" finished-at="2024-10-28T07:11:40 IST" duration-ms="11676" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[laks@yahoo.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[xyz]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[invalid]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_LoginAccount -->
        <test-method signature="verify_LoginAccount(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_LoginTestDDT@21a21c64]" started-at="2024-10-28T07:11:40 IST" name="verify_LoginAccount" data-provider="LoginData" finished-at="2024-10-28T07:11:46 IST" duration-ms="6003" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[abc123@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[test@123]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[valid]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_LoginAccount -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testCases.TC02_LoginTestDDT@21a21c64]" started-at="2024-10-28T07:11:46 IST" name="tearDown" finished-at="2024-10-28T07:11:48 IST" duration-ms="1843" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testCases.TC02_LoginTestDDT -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
